import os

ELASTIC_SEARCH_HOST = os.getenv("ELASTIC_SEARCH_HOST", 'localhost')
ELASTIC_SEARCH_PORT = os.getenv("ELASTIC_SEARCH_PORT", 9243)
ELASTIC_SEARCH_USER = os.getenv("ELASTIC_SEARCH_USER", 'elastic')
ELASTIC_SEARCH_PASS = os.getenv("ELASTIC_SEARCH_PASS", 'elastic')
ELASTIC_SEARCH_AUTH = (ELASTIC_SEARCH_USER, ELASTIC_SEARCH_PASS)
